### ISSUE TITLE
Merge -g and -t start.py options

### ISSUE THREAD

**Issue by Lindisse** [nstockton/mapperproxy-mume#5]
Hello,

I'm wondering if it would'nt be better to merge the -g and -t options of start.py. I indeed feel there's a redudancy actually. I'm pondering two possibilities:

```python
# First possibility: interface option -i.
group.add_argument("-i", "--interface", help="Define the user interface", choices=["text", "hc", "sighted"], default="text")

# Second possibility: GUI option -g.
# the default is a text only interface, but option -g sets up a GUI.
# If the -g option has no argument, the constant "hc" is used.
group.add_argument("-g", "--gui", help="Use a GUI (requires pyglet).", nargs="?", choices=["hc", "sighted"], default=False, const="hc")
```

In both case, the "-t" option is removed, the text only interface being the default.

What do you think about this?

**Comment by nstockton** [comment]
I like the idea of a -i/--interface option. This would allow us to default to either GUI or text mode, and has the advantage of allowing the user to explicitly start the map in text-only mode.

**Comment by nstockton** [comment]
From a0ab2aa5f8e122bad9f00d300efa6a5817b5ec48

Removed the /g/--gui and -t/--text arguments in start.py. There is now a single argument which replaces them, -i or --interface. See 'start.py --help' for details.
